# ──────────────────────────────────────────────
# ZeroDay Guardian — Namespace
# ──────────────────────────────────────────────
apiVersion: v1
kind: Namespace
metadata:
  name: zeroday-guardian
  labels:
    name: zeroday-guardian
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
