export const platformArchitecture = {
  version: "2026.03",
  name: "ZeroDay Guardian",
  backend: {
    gateway: "Express",
    services: [
      "auth",
      "users",
      "osint",
      "scans",
      "threat_detection",
      "adaptive_ai",
      "recommendations",
      "notifications",
      "labs",
      "files",
      "telemetry",
    ],
    middleware: [
      "cors",
      "helmet",
      "rate_limit",
      "csrf",
      "input_sanitize",
      "audit_log",
      "request_guard",
    ],
    asyncJobs: ["scan_worker", "osint_monitor", "ai_retry_queue"],
  },
  database: {
    primary: "PostgreSQL",
    cache: "Redis",
    analytics: "read_replicas_or_timescale",
    storage: ["users", "progress", "rewards", "recommendations", "events", "scan_reports"],
  },
  ai: {
    routing: "zorvix_rule_engine",
    primaryProvider: "rule_based",
    fallbackProvider: "local_fallback",
    strategies: ["rules_first", "cache_first", "actionable_output"],
    outputStyle: "short_actionable_bullets",
  },
  frontend: {
    framework: "React",
    transport: ["SSE", "HTTP"],
    ux: ["real_time_updates", "premium_cards", "mobile_first", "fast_loading"],
  },
  performance: {
    p95LatencyMs: 2000,
    cacheTtlSeconds: 120,
    rateLimitDefault: "30/5m",
    sseHeartbeatSeconds: 25,
  },
  security: {
    auth: "JWT + refresh sessions",
    encryption: ["TLS", "password_hashing"],
    abusePrevention: ["rate_limit", "anomaly_checks"],
    audit: ["request_id", "structured_logs"],
  },
  extensibility: {
    modules: "plug-in style service boundaries",
    apiVersioning: "versioned routes + schema",
    featureFlags: "config-driven",
  },
  updatedAt: new Date().toISOString(),
};
